
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Watchira Mingkhwan  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Ubon Ratchathani, Thailand

## Social Profiles




# Update all the sections by editing the files inside _includes folder.
